"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiList = void 0;
const jsx_runtime_1 = require("react/jsx-runtime");
const lucide_react_1 = require("lucide-react");
const ApiList = ({ apis, onEditApi, onDeleteApi, onToggleApi, onAddCase, onEditCase, onDeleteCase, onSetActiveCase }) => {
    const getMethodClass = (method) => {
        return `method-badge method-${method.toLowerCase()}`;
    };
    const getStatusClass = (status) => {
        return `status-badge status-${status}`;
    };
    return ((0, jsx_runtime_1.jsxs)("div", { className: "p-4 h-full overflow-y-auto", children: [(0, jsx_runtime_1.jsx)("h2", { className: "text-lg font-semibold text-gray-900 mb-4", children: "APIs" }), apis.length === 0 ? ((0, jsx_runtime_1.jsx)("div", { className: "text-center text-gray-500 py-8", children: (0, jsx_runtime_1.jsx)("p", { children: "No APIs added yet" }) })) : ((0, jsx_runtime_1.jsx)("div", { className: "space-y-4", children: apis.map((api) => ((0, jsx_runtime_1.jsxs)("div", { className: "card p-4", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-center justify-between mb-3", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-center space-x-2", children: [(0, jsx_runtime_1.jsx)("span", { className: getMethodClass(api.method), children: api.method }), (0, jsx_runtime_1.jsx)("button", { onClick: () => onToggleApi(api.id), className: `p-1 rounded ${api.isEnabled
                                                ? 'text-green-600 hover:bg-green-50'
                                                : 'text-gray-400 hover:bg-gray-50'}`, title: api.isEnabled ? 'Disable API' : 'Enable API', children: api.isEnabled ? (0, jsx_runtime_1.jsx)(lucide_react_1.Play, { className: "w-4 h-4" }) : (0, jsx_runtime_1.jsx)(lucide_react_1.Pause, { className: "w-4 h-4" }) })] }), (0, jsx_runtime_1.jsxs)("div", { className: "flex items-center space-x-1", children: [(0, jsx_runtime_1.jsx)("button", { onClick: () => onEditApi(api), className: "p-1 text-gray-600 hover:text-blue-600 hover:bg-blue-50 rounded", title: "Edit API", children: (0, jsx_runtime_1.jsx)(lucide_react_1.Edit, { className: "w-4 h-4" }) }), (0, jsx_runtime_1.jsx)("button", { onClick: () => onDeleteApi(api.id), className: "p-1 text-gray-600 hover:text-red-600 hover:bg-red-50 rounded", title: "Delete API", children: (0, jsx_runtime_1.jsx)(lucide_react_1.Trash2, { className: "w-4 h-4" }) })] })] }), (0, jsx_runtime_1.jsxs)("div", { className: "mb-3", children: [(0, jsx_runtime_1.jsx)("h3", { className: "font-medium text-gray-900", children: api.name }), (0, jsx_runtime_1.jsx)("p", { className: "text-sm text-gray-600 font-mono", children: api.path }), api.description && ((0, jsx_runtime_1.jsx)("p", { className: "text-sm text-gray-500 mt-1", children: api.description }))] }), (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-center justify-between mb-2", children: [(0, jsx_runtime_1.jsx)("h4", { className: "text-sm font-medium text-gray-700", children: "Response Cases" }), (0, jsx_runtime_1.jsxs)("button", { onClick: () => onAddCase(api.id), className: "btn-secondary text-xs py-1 px-2", title: "Add Response Case", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Plus, { className: "w-3 h-3 mr-1" }), "Add Case"] })] }), api.cases.length === 0 ? ((0, jsx_runtime_1.jsx)("p", { className: "text-xs text-gray-500", children: "No response cases defined" })) : ((0, jsx_runtime_1.jsx)("div", { className: "space-y-2", children: api.cases.map((responseCase) => ((0, jsx_runtime_1.jsxs)("div", { className: `flex items-center justify-between p-2 rounded border ${api.activeCase === responseCase.id
                                            ? 'border-primary-200 bg-primary-50'
                                            : 'border-gray-200 bg-gray-50'}`, children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-center space-x-2 flex-1", children: [(0, jsx_runtime_1.jsx)("button", { onClick: () => onSetActiveCase(api.id, responseCase.id), className: `p-1 rounded ${api.activeCase === responseCase.id
                                                            ? 'text-primary-600'
                                                            : 'text-gray-400 hover:text-primary-600'}`, title: api.activeCase === responseCase.id
                                                            ? 'Active case'
                                                            : 'Set as active case', children: (0, jsx_runtime_1.jsx)(lucide_react_1.Circle, { className: `w-3 h-3 ${api.activeCase === responseCase.id ? 'fill-current' : ''}` }) }), (0, jsx_runtime_1.jsxs)("div", { className: "flex-1 min-w-0", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-center space-x-2", children: [(0, jsx_runtime_1.jsx)("span", { className: "text-xs font-medium text-gray-900 truncate", children: responseCase.name }), (0, jsx_runtime_1.jsx)("span", { className: getStatusClass(responseCase.status), children: responseCase.status })] }), responseCase.description && ((0, jsx_runtime_1.jsx)("p", { className: "text-xs text-gray-500 truncate", children: responseCase.description }))] })] }), (0, jsx_runtime_1.jsxs)("div", { className: "flex items-center space-x-1", children: [(0, jsx_runtime_1.jsx)("button", { onClick: () => onEditCase(api.id, responseCase.id), className: "p-1 text-gray-500 hover:text-blue-600 hover:bg-blue-50 rounded", title: "Edit Case", children: (0, jsx_runtime_1.jsx)(lucide_react_1.Edit, { className: "w-3 h-3" }) }), (0, jsx_runtime_1.jsx)("button", { onClick: () => onDeleteCase(api.id, responseCase.id), className: "p-1 text-gray-500 hover:text-red-600 hover:bg-red-50 rounded", title: "Delete Case", children: (0, jsx_runtime_1.jsx)(lucide_react_1.Trash2, { className: "w-3 h-3" }) })] })] }, responseCase.id))) }))] })] }, api.id))) }))] }));
};
exports.ApiList = ApiList;
